### ISSUE TITLE
How x y r b and box_landmark defined? 

### ISSUE THREAD

**Issue by opentld** [dlunion/DBFace#5]
In your code main.py
        x, y, r, b = box[:, cy, cx]
        xyrb = (np.array([cx, cy, cx, cy]) + [-x, -y, r, b]) * stride
        x5y5 = landmark[:, cy, cx]
        x5y5 = (common.exp(x5y5 * 4) + ([cx]*5 + [cy]*5)) * stride
        box_landmark = list(zip(x5y5[:5], x5y5[5:]))
-------------------------------------------------------------------------------------------------
I can't understand how the landmark is calculated?  What does x y r b mean?
@dlunion

**Comment by dlunion** [comment]
`x y r b` it means:
x = box.left (or box.xmin)
y = box.top (or box.ymin)
r = box.right (or box.xmax)
b = box.bottom (or box.ymax)

landmark is `xxxxxyyyyy format` in 10 channels output.
```python
OriginalLandmark = (common.exp(x5y5 * 4) + cellCenter) * stride
box_landmark = list(zip(OriginalLandmark [:5], OriginalLandmark [5:]))
```
Here,
`cellCenter` it means cx and cy
`OriginalLandmark` is xxxxxyyyyy format.
`box_landmark` is [[x, y], [x, y], [x, y], [x, y], [x, y]] format.  
`common.exp` is special `exp` function
`[cx]*5 + [cy]*5` is equivalent to `[cx, cx, cx, cx, cx, cy, cy, cy, cy, cy]`

**Comment by opentld** [comment]
> `x y r b` it means:
> x = box.left (or box.xmin)
> y = box.top (or box.ymin)
> r = box.right (or box.xmax)
> b = box.bottom (or box.ymax)
> 
> landmark is `xxxxxyyyyy format` in 10 channels output.
> 
> ```python
> OriginalLandmark = (common.exp(x5y5 * 4) + cellCenter) * stride
> box_landmark = list(zip(OriginalLandmark [:5], OriginalLandmark [5:]))
> ```
> 
> Here,
> `cellCenter` it means cx and cy
> `OriginalLandmark` is xxxxxyyyyy format.
> `box_landmark` is [[x, y], [x, y], [x, y], [x, y], [x, y]] format.
> `common.exp` is special `exp` function
> `[cx]*5 + [cy]*5` is equivalent to `[cx, cx, cx, cx, cx, cy, cy, cy, cy, cy]`

Thank you very much!  
I think x,y,r,b represent the coordinates relative to the cell center, but what does 'stride' mean? why multiply by  stride ?
@dlunion

**Comment by opentld** [comment]
gate = 1
    base = np.exp(1)
    if abs(v) < gate:    # 如果v的绝对值小于1，那么exp的结果为v * np.exp(1)
        return v * base

    if v > 0:            # v的绝对值大于1，并且v为正，那么exp的结果为np.exp(v)；否则，exp结果为-np.exp(-v)
        return np.exp(v) 
    else:
        return -np.exp(-v)
------------------------------------------------------------
common.exp is special exp function, but I can't understand why is the method of calculating exp different for different values?
@dlunion

**Comment by opentld** [comment]
gate = 1
    base = np.exp(1)
    if abs(v) < gate:    # 如果v的绝对值小于1，那么exp的结果为v * np.exp(1)
        return v * base
    if v > 0:            # v的绝对值大于1，并且v为正，那么exp的结果为np.exp(v)；否则，exp结果为-np.exp(-v)
        return np.exp(v) 
    else:
        return -np.exp(-v)
------------------------------------------------------------
common.exp is special exp function, but I can't understand why is the method of calculating exp different for different values?
@dlunion

**Comment by dlunion** [comment]
他是来自于common.log的一个反函数实现。common.log的函数实质上是一种类似sigmoid的S型函数。目的是当landmark不依赖人脸框仅仅依赖人脸中心的时候，需要对其值进行压缩而设计。

当使用log时，由于landmark的值域是实数域（有正负），而log对于0和负数没有定义，因此对log进行了分段实现（类似smoothL1的设计），使得他满足landmark的需求

**Comment by opentld** [comment]
> 他是来自于common.log的一个反函数实现。common.log的函数实质上是一种类似sigmoid的S型函数。目的是当landmark不依赖人脸框仅仅依赖人脸中心的时候，需要对其值进行压缩而设计。
> 
> 当使用log时，由于landmark的值域是实数域（有正负），而log对于0和负数没有定义，因此对log进行了分段实现（类似smoothL1的设计），使得他满足landmark的需求

明白了，多谢！
