### ISSUE TITLE
尝试用opencv4.3.0的dnn读取dbface.pth失败

### ISSUE THREAD

**Issue by opentld** [dlunion/DBFace#6]
错误提示如下：
torch_importer.cpp:1022: error: (-213:The function/feature is not implemented) Unsupported Lua type in function 'cv::dnn::dnn4_v20200310::TorchImporter::readObject'

为什么是Lua type？我看了你的DBFace.py，不知道是哪里的定义，使得cv::dnn无法读取模型？
@dlunion

**Comment by dlunion** [comment]
这个可能是因为torch版本造成的，我不是太确定什么原因。我一般会使用tensorRT来实现加速。

**Comment by dlunion** [comment]
[这里](https://github.com/dlunion/tensorRTIntegrate/blob/master/src/examples/dbface.cpp)是对应的tensorRT实现

**Comment by opentld** [comment]
watch star fork 三连击！
多谢大神：）
